### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by snd** [snd/fragments-user-clientside#1]
## roadmap
- [x] serverside that serves single page app
- [x] basic gulp build script for the clientside js
- [x] wire everything up that hinoki works perfectly on the client and adding new factories is as easy as on the server
- [x] for routing keep a cursor containing the current url in sync with the current url across anchor clicks and push state events
- [x] then simply implement routing by dispatching on that url-cursor and enabling/disabling "page"-components
- [x] integrate http://getbootstrap.com/
- [x] working login form
- [x] send login request to api
- [x] add some fake users
- [x] validation for login form that reuses serverside validation rules
  - [x] waechter on the client side
  - [x] make validation rules available to clientside
  - [x] run sync validation every time user inputs change
  - [x] show validation errors next to form fields
  - [x] only show validation errors after first click on login
  - [x] gray out login button if validation errors after first click on login
  - [x] show green glyphicon-ok inside valid form fields
- [x] make login button style primary
- [x] [document react and cursor gotchas](https://github.com/snd/fragments-user-clientside/blob/master/log.md)
- [x] refactor the way the login form state is updated
- [x] improve initial validation messages
- [x] show error in form when login failed
  - [x] as an alert
  - [x] handle both json and strings
- [x] handle successful login
  - [x] keep currentUser and token in a cursor
- [x] make navigation change based on login status
- [x] store user token in cookie to persist it across refreshs
- [x] load user on refresh if token is present 
- [x] make enter key submit form
- [x] we're not continuing with https://github.com/caseywebdev/cursors. find the next cursors library/solution that looks promising
  - [findings are documented here](https://github.com/snd/fragments-user-clientside/blob/master/cursor-library-evaluation.md)
- [x] use a different cursor solution
  - [x] remove code and libs that are no longer needed
- [x] fix gulp ruby sass
- [x] find way to keep bower deps up to date
- [x] clean `page` cursor (on mounting)
- [ ] working user table
  - [x] load data on `componentDidMount` using https://github.com/ded/reqwest
  - [x] just list all the users for a start
  - [x] serialize/update filter state to url query params automatically
    - exactly the siv params
    - `path` stores query params (its the only place its stored)
    - `setQuery`
    - `getQuery`
  - [x] sorting (and default sort)
  - [ ] momentjs and pretty printing of dates
  - [ ] put the filtering stuff into a modal
  - [x] pagination: page `[input for page number]` of `{page count}` `[<]` `[>]` with `[input for per page]` per page
    - [x] immediate query
  - [ ] make it work/functional
  - [ ] then make it pretty
- [x] make clientside redirects (nagivate) work
- [x] complete two-way-binding: pushState automatically if the `path` cursor changes
- [ ] handle server responses with error status codes by setting an `error` cursor to the response which if set pops up a modal with the raw error data and is cleared when the modal is closed
  - "please refresh"
  - "we've been notified"
  - "we apologize for the situation"
- [ ] improve workflow with auto-compile and auto-refresh to speed up development
- [x] user detail view
- [x] parse rights string
  - preferably on server side
- [ ] user delete if currentUser has that right
- [ ] user create if currentUser has that right
  - [ ] debounced async email taken validation
- [ ] user update if currentUser has that right
- [ ] exhaustive user table filtering on the clientside which uses https://github.com/snd/siv
  - [ ] good UX ???
### nice to have
- [ ] hinoki source for autogeneration of clientside data accessor functions
- [x] use isomorphic url-patterns clientside
- [ ] look at https://github.com/ubolonton/js-csp and see if its better suited to your problems than http://highlandjs.org/
- [ ] multiple lifetimes on the client 
  - extracted into issue https://github.com/snd/fragments-user-clientside/issues/2
- possibly reinject in react components methods when using dependencies that might not be available on the server (example: `login` on the clientside) in order to make react components work on the server without mocking out all the clientside stuff
- [x] use a different cursor system if https://github.com/caseywebdev/cursors doesn't do the job
  - consider writing your own - it's easy and you'll then have full control
- [x] find better unified name for `path` and use it everywhere (helpers, cursor, ...)
- [ ] find better name for `page` cursor
- [ ] material design
- [ ] make button for collapsed nav work
- [ ] production gulp tasks
  - [ ] minify / uglify
  - [ ] dont expose dev js on production
- [x] make the state/tree/cursor a dependency so you can define functions that work directly on it
  - navigate
  - setError
- [x] `navigate` function as a more convenient way to update the `path` cursor
  - don't know about this. its pretty explicit to update the path cursor directly and can often be bundled with other updates. each action that has to update state should preferably and with a single update anyway.
- [x] would be best to `pushState` if and only if `path` cursor changes and to change `path` cursor when relative anchor is clicked or manually in code
  - changing `path` cursor = navigating
- [ ] add `active` class to active links
- [x] only route certain routes when user is logged in
- [x] catch invalid `path`s clientside and show 404
- [ ] always redirect to login when user is not logged in
- [ ] fetch as much as possible using npm and not bower
- [ ] https://github.com/rstacruz/nprogress
### nice to have changes to external libraries
- [ ] port https://github.com/snd/fragments-user urls to https://github.com/snd/url-pattern and use `.stringify`
- [ ] support things like `GET pattern, stringThatIsNameOfRequestHandlerDependency` in https://github.com/snd/fragments
